### PR TITLE
Updated readme for 2024 04 version

### PR DESCRIPTION
**Pull request by DongrongLi**
Updated README file for the 2024-04-version

### CODE REVIEW

**Comment by robertkwapisz** [comment]
Can you move the old version into development directory. Also an image of the breadboard would be nice, one that clearly shows the components without any surrounding clutter. The description at the top is unfinished, if you don't know the changes that were made to this design from the previous we can talk about it (I think they should all be documented in a trello card somewhere, I may be forgetting all the changes that were made as well). Re-request my review when you're ready so that I get an email notification.

**Comment by robertkwapisz** [comment]
As with other pull request there are some grammar things to fix up, I can help with these too.

**Comment by robertkwapisz** [comment]
can you update the picture to show that 2 of the wavelplate mounts are used

**Review by jayich — DISMISSED** [review]
lgtm.

**Review by jayich — APPROVED** [review]
lgtm.

**Pull request merged**
